##предавам се санкционирайте ме##

name: CI test
on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install

      - name: dedjustded
        run: echo "DEDJUSTDED: ${{ secrets.DEDJUSTDED }}"

  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install

      - name: dedjustded_unit_tests
        run: echo "DEDJUSTDED (UNIT TESTS): ${{ secrets.DEDJUSTDED_UNIT_TESTS }}"

      - name: Run Unit Tests
        run: npm run test:unit
