name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Set permission for Mocha
      run: chmod +x ./node_modules/.bin/mocha
    - name: Setup Playwright
      uses: microsoft/playwright-github-action@v1
    - name: run unit tests
      run: npm run test:unit
    - name: softuni username
      run: echo "dedjustded"

      
  build-ui:
    needs: build-test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Setup Playwright
      uses: microsoft/playwright-github-action@v1
    - name: Run UI tests
      run: npm run test:ui

  deploy:
    needs: build-ui
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}

      
